    repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v2.0.0
          hooks:
          - id: flake8
      - repo: https://github.com/pycqa/isort
          rev: 5.12.0
          hooks:
          - id: isort
